# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev53+g1cb4c39.d20230322'
__version_tuple__ = version_tuple = (0, 1, 'dev53', 'g1cb4c39.d20230322')
