# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev28+gd3388ef.d20230512'
__version_tuple__ = version_tuple = (0, 1, 'dev28', 'gd3388ef.d20230512')
